"""Update interview model with conversation_history and remove old fields

Revision ID: 4243cd47bcce
Revises: 
Create Date: 2026-01-02 00:53:04.759663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4243cd47bcce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Check if tables exist before altering (idempotent migration)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'interviews' not in tables:
        # Tables don't exist yet, skip (they'll be created by Base.metadata.create_all in main.py)
        return
    
    # Tables exist, apply alterations (check columns to make idempotent)
    columns = [col['name'] for col in inspector.get_columns('interviews')]
    
    if 'conversation_history' not in columns:
        op.add_column('interviews', sa.Column('conversation_history', sa.JSON(), nullable=True))
    if 'resume_context' not in columns:
        op.add_column('interviews', sa.Column('resume_context', sa.JSON(), nullable=True))
    if 'turn_count' not in columns:
        op.add_column('interviews', sa.Column('turn_count', sa.Integer(), nullable=False, server_default='0'))
    if 'questions' in columns:
        op.drop_column('interviews', 'questions')
    if 'total_questions' in columns:
        op.drop_column('interviews', 'total_questions')
    if 'answers' in columns:
        op.drop_column('interviews', 'answers')
    if 'current_question_index' in columns:
        op.drop_column('interviews', 'current_question_index')
    
    if 'resumes' in tables:
        resume_columns = [col['name'] for col in inspector.get_columns('resumes')]
        if 'raw_text' in resume_columns:
            op.drop_column('resumes', 'raw_text')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('interviews', sa.Column('current_question_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('interviews', sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('interviews', sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('interviews', sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('interviews', 'turn_count')
    op.drop_column('interviews', 'resume_context')
    op.drop_column('interviews', 'conversation_history')
    # ### end Alembic commands ###

